### ISSUE TITLE
invalid result for nested array

### ISSUE THREAD

**Issue by senid231** [lukeed/flattie#2]
$ npm install --save flat-obj
    ...
    + flat-obj@2.2.0
    $ node

```js
> flatObj = require('flat-obj');
[Function: flatten]
> flatObj({a: null, b: 'c', d: [1,2] })
{ b: 'c', d: [ {}, {} ] }
> flatObj({a: null, b: 'c', d: [1,2], e: { f: ['g', 'h']}})
{ b: 'c', d: [ {}, {} ], e_f: [ { '0': 'g' }, { '0': 'h' } ] }
```

**Comment by senid231** [comment]
Also, I think we should keep a key if a value is null (or at least add argument `preserve_null=false`) and remove only keys which value is `undefined`

**Comment by lukeed** [comment]
Thanks, I saw this last night too.

This module is actually a couple years old, so I was sprucing it up for current range. Was planning on removing the nullish check altogether for next major

**Comment by lukeed** [comment]
We can have a different discussion about `null` purging, but I decided that (at least for now) it's something I want to continue doing.

Fixed/changed Array-handling, so that its indices are always included as part of the flattened output:

```js
const input = [
  [1, 2, null, 3, 4],
  ['foo', 'bar', ['hello', null, 'world'], 'baz'],
  [6, 7, 8, undefined, 9]
];

assert.deepEqual(
  flat(input), {
    '0_0': 1,
    '0_1': 2,
    '0_3': 3,
    '0_4': 4,
    '1_0': 'foo',
    '1_1': 'bar',
    '1_2_0': 'hello',
    '1_2_2': 'world',
    '1_3': 'baz',
    '2_0': 6,
    '2_1': 7,
    '2_2': 8,
    '2_4': 9,
  }
);
```

Works when an objects' keys are arrays too, of course:

```js
const  input = { a: 1, b:[{ foo:1, bar:2 }], c: 3 };

assert.deepEqual(
  flat(input, '.'), { 
    'a': 1, 
    'b.0.foo': 1, 
    'b.0.bar': 2, 
    'c': 3
  }
)
```
