### ISSUE TITLE
Possible to keep null values?

### ISSUE THREAD

**Issue by saibotsivad** [lukeed/flattie#3]
Right now I'm using a less-awesome library for merging objects as part of some [JSON:API](http://jsonapi.org/) tooling, but specs for JSON:API treat `null` as a meaningful value (used to specify deleting a property on a sparse update).

I see you're checking for null explicitly `if (val == null)` I'm wondering if there might be a way to specify keeping `null`?

❤️ 🙇

**Comment by lukeed** [comment]
Yes, I meant to do this but forgot 🤦 

Only `undefined`/holes should be ignored, so that it more closely aligns. 
But I'll keep `NaN` values (`JSON.stringify` converts that to `null` anyway)

**Comment by lukeed** [comment]
I'm thinking I prefer this instead, actually:

```js
flattie(input, glue = '.', toNullish = false)
```

If `toNullish` is set, then `null` and `undefined` can be written. 
For JSON:API, this shouldn't matter since any client sending data (via `JSON.stringify` for body) will have `undefined` stripped already, which also means it won't be there on the server-side.

Thoughts?

**Comment by tripodsgames** [comment]
> I'm thinking I prefer this instead, actually:
> 
> ```js
> flattie(input, glue = '.', toNullish = false)
> ```
> 
> If `toNullish` is set, then `null` and `undefined` can be written.
> For JSON:API, this shouldn't matter since any client sending data (via `JSON.stringify` for body) will have `undefined` stripped already, which also means it won't be there on the server-side.
> 
> Thoughts?

For internal object structure I use undefined when I need the key. So it's good to keep it i think.

**Comment by lukeed** [comment]
@tripodsgames Thanks! Doing it today, just adding tests
